// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { awscdk } from "projen";
import { applyDefaultConfig, cdkAppDefaultOptions } from "../config";
import { deepMerge } from "../utils";
import type { AwsCdkTypeScriptAppProjectOptions } from "./awscdk-typescript-app-options.generated";

export { AwsCdkTypeScriptAppProjectOptions } from "./awscdk-typescript-app-options.generated";

export class AwsCdkTypeScriptAppProject extends awscdk.AwsCdkTypeScriptApp {
    constructor(options: AwsCdkTypeScriptAppProjectOptions) {
        const { mise, vitest, vitestOptions, ...baseOptions } = options;

        super(deepMerge<awscdk.AwsCdkTypeScriptAppOptions>(cdkAppDefaultOptions, baseOptions));

        applyDefaultConfig(this, vitest, vitestOptions, mise);
    }
}
