// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { awscdk } from "projen";
import { Mise } from "../components/mise";
import { Vitest } from "../components/vitest";
import { applyDefaults, defaultOptions } from "../config";
import { deepMerge } from "../utils";
import type { AwsCdkTypeScriptAppProjectOptions } from "./awscdk-typescript-app-options.generated";


export { AwsCdkTypeScriptAppProjectOptions } from "./awscdk-typescript-app-options.generated";


/**
 * AwsCdkTypeScriptAppProject with standard configuration and component integration
 *
 * Extends Projen's base class with opinionated defaults and automatic component setup.
 */
export class AwsCdkTypeScriptAppProject extends awscdk.AwsCdkTypeScriptApp {
    /**
     * @param options - Project configuration
     */
    constructor(options: AwsCdkTypeScriptAppProjectOptions) {
        /* Separate component configuration from base Projen options */
        const { mise, vitest, vitestOptions, ...baseOptions } = options;

        /* Merge default configuration with user options and initialize base class */
        super(deepMerge<awscdk.AwsCdkTypeScriptAppOptions>(defaultOptions.awscdk.AwsCdkTypeScriptApp, baseOptions));

        /* Apply component defaults and instantiate enabled components */
        applyDefaults(this, [{ component: Mise, enabled: mise }, { component: Vitest, enabled: vitest, options: vitestOptions }]);
    }
}
