// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { awscdk } from "projen";
import { Mise } from "../components/mise";
import { Vitest } from "../components/vitest";
import { applyDefaults, defaultOptions } from "../config";
import { deepMerge } from "../utils";
import type { AwsCdkConstructLibraryProjectOptions } from "./awscdk-construct-library-options.generated";

export { AwsCdkConstructLibraryProjectOptions } from "./awscdk-construct-library-options.generated";

/**
 * AwsCdkConstructLibraryProject with standard configuration and component integration
 *
 * Extends Projen's base class with opinionated defaults and automatic component setup.
 */
export class AwsCdkConstructLibraryProject extends awscdk.AwsCdkConstructLibrary {
    /**
     * @param options - Project configuration
     */
    constructor(options: AwsCdkConstructLibraryProjectOptions) {
        /* Separate component configuration from base Projen options */
        const { mise, vitest, ...baseOptions } = options;

        /* Merge default configuration with user options and initialize base class */
        super(deepMerge<awscdk.AwsCdkConstructLibraryOptions>(defaultOptions.awscdk.AwsCdkConstructLibrary, baseOptions));

        /* Apply component defaults and instantiate enabled components */
        applyDefaults(this, [{ component: Mise, enabled: mise }, { component: Vitest, enabled: vitest }]);
    }
}