// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { cdk } from "projen";
import { applyDefaultConfig, jsiiProjectDefaultOptions } from "../config";
import { deepMerge } from "../utils";
import type { JsiiProjectOptions } from "./jsii-options.generated";

export { JsiiProjectOptions } from "./jsii-options.generated";

export class JsiiProject extends cdk.JsiiProject {
    constructor(options: JsiiProjectOptions) {
        const { mise, vitest, vitestOptions, ...baseOptions } = options;

        super(deepMerge<cdk.JsiiProjectOptions>(jsiiProjectDefaultOptions, baseOptions));

        applyDefaultConfig(this, vitest, vitestOptions, mise);
    }
}
