// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { cdk } from "projen";
import { Homebrew } from "../components/homebrew";
import { Mise } from "../components/mise";
import { TypeDoc } from "../components/typedoc";
import { Vitest } from "../components/vitest";
import { applyDefaults, defaultOptions } from "../config";
import { deepMerge } from "../utils";
import type { JsiiProjectOptions } from "./jsii-options.generated";

export { JsiiProjectOptions } from "./jsii-options.generated";

/**
 * JsiiProject with standard configuration and component integration
 *
 * Extends Projen's base class with opinionated defaults and automatic component setup.
 */
export class JsiiProject extends cdk.JsiiProject {
    /**
     * @param options - Project configuration
     */
    constructor(options: JsiiProjectOptions) {
        /* Separate component configuration from base Projen options */
        const { homebrew, mise, vitest, typeDoc, ...baseOptions } = options;

        /* Merge default configuration with user options and initialize base class */
        super(deepMerge<cdk.JsiiProjectOptions>(defaultOptions.cdk.JsiiProject, baseOptions));

        /* Apply component defaults and instantiate enabled components */
        applyDefaults(this, [{ component: Homebrew, enabled: homebrew }, { component: Mise, enabled: mise }, { component: Vitest, enabled: vitest }, { component: TypeDoc, enabled: typeDoc }]);
    }
}