// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { typescript } from "projen";
import { Mise } from "../components/mise";
import { Vitest } from "../components/vitest";
import { applyDefaults, defaultOptions } from "../config";
import { deepMerge } from "../utils";
import type { TypeScriptProjectOptions } from "./typescript-options.generated";


export { TypeScriptProjectOptions } from "./typescript-options.generated";


/**
 * TypeScriptProject with standard configuration and component integration
 *
 * Extends Projen's base class with opinionated defaults and automatic component setup.
 */
export class TypeScriptProject extends typescript.TypeScriptProject {
    /**
     * @param options - Project configuration
     */
    constructor(options: TypeScriptProjectOptions) {
        /* Separate component configuration from base Projen options */
        const { mise, vitest, vitestOptions, ...baseOptions } = options;

        /* Merge default configuration with user options and initialize base class */
        super(deepMerge<typescript.TypeScriptProjectOptions>(defaultOptions.typescript.TypeScriptProject, baseOptions));

        /* Apply component defaults and instantiate enabled components */
        applyDefaults(this, [{ component: Mise, enabled: mise }, { component: Vitest, enabled: vitest, options: vitestOptions }]);
    }
}
